describe("nvim-java basic tests", function()
  it("should load java configuration", function()
    local success = pcall(require, 'java')
    assert(success, "java module should load without errors")
  end)
  
  it("should have java executable available", function()
    local handle = io.popen("java -version 2>&1")
    local result = handle:read("*a")
    handle:close()
    assert(result:match("openjdk version"), "Java should be available")
  end)
end)