name: Test nvim-java Plugin

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
  workflow_call:
  repository_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    
    - name: Setup Neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: nightly
    
    - name: Setup neovim config
      run: |
        mkdir -p ~/.config/nvim
        cp nvim-config/init.lua ~/.config/nvim/init.lua
        
    - name: Install plenary.nvim for testing
      run: |
        mkdir -p ~/.local/share/nvim/site/pack/deps/start/plenary.nvim
        git clone https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/deps/start/plenary.nvim
    
    - name: Wait for Mason packages to install
      run: |
        nvim --headless -c "set runtimepath+=$(pwd)" -c "lua require('utils.utils').wait_for_mason_install()" -c "qa!"
    
    - name: Run tests
      run: |
        nvim --headless -c "lua require('plenary.test_harness').test_directory('tests')" -c "qa!"
